### ISSUE TITLE
release: make v0.0.3 release

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/invenio-files-js#26]
See 6a8c579dd3e99f12d151fdfd2ddac16b2c52baba

- Remove ``RELEASE-NOTES.rst``

Problem with travis not automatically releasing.

**Comment by roksys** [comment]
Isn't it already done -  https://github.com/inveniosoftware/invenio-files-js/commit/74fbef25f2db2f39995091ed2ccb629f5ced5ac3 ?

**Comment by kprzerwa** [comment]
closing as done already
